// <auto-generated />
namespace NewFakeBookMarkIII.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TestVIII : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestVIII));
        
        string IMigrationMetadata.Id
        {
            get { return "201512152107490_TestVIII"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
